### ISSUE TITLE
Unable to find dependency

### ISSUE THREAD

**Issue by arkeine** [yarinvak/graphql-spring-annotations#4]
Hello, 

I have an issue to download the dependency with maven and gradle.

When I use that 
```
dependencies {
    compile "io.github.enigmatis:graphql-spring-annotations:0.1.5"
}
```
 in a gradel project it will say `Could not find io.github.enigmatis:graphql-spring-annotations:0.1.5`.

I have tried to add a new repository 
```
maven{
     url "https://maven.pkg.github.com/yarinvak/graphql-spring-annotations"
 }
```
but without success.

I have the same issue with maven.

Am I doing something wrong ?

**Comment by yarinvak** [comment]
add jcenter to the repositories
```
repositories {
    jcenter()
}

**Comment by arkeine** [comment]
Thank you very much, it works know 👍
